In [2]:
import sys
sys.path.append('/Users/marie/Documents/Research/sge/Julia/VariabilityIndexes')
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from variability.lightcurve import LightCurve
from lc_functions import  clean_light_curves
from tqdm import tqdm
import seaborn as sns
from scipy import interpolate

In [3]:
bad_hjds_list_J = np.load('/Users/marie/Documents/Research/sge/CygOB2 - DATA/UKIRT2007/J_hjdsremoved.npy', allow_pickle=True)
bad_hjds_list_H = np.load('/Users/marie/Documents/Research/sge/CygOB2 - DATA/UKIRT2007/H_hjdsremoved.npy', allow_pickle=True)
bad_hjds_list_K= np.load('/Users/marie/Documents/Research/sge/CygOB2 - DATA/UKIRT2007/K_hjdsremoved.npy', allow_pickle=True)


In [5]:
print(bad_hjds_list_J)
print(bad_hjds_list_H)
print(bad_hjds_list_K)

[54208.55255 54383.23101 54388.20301 54388.20524 54388.20412]
[54388.23896 54240.62712 54388.24007]
[54388.24275 54240.63077 54240.63293 54388.2461  54388.24499]


In [7]:
bad_hjds_list = np.concatenate((bad_hjds_list_J, bad_hjds_list_H, bad_hjds_list_K))
bad_hjds_list

array([54208.55255, 54383.23101, 54388.20301, 54388.20524, 54388.20412,
       54388.23896, 54240.62712, 54388.24007, 54388.24275, 54240.63077,
       54240.63293, 54388.2461 , 54388.24499])

In [8]:
if __name__ == "__main__":
    input_dir = '/Users/marie/Documents/Research/sge/CygOB2 - DATA/UKIRT2007/teste/'
    output_dir = '/Users/marie/Documents/Research/sge/CygOB2 - DATA/UKIRT2007/clean_teste/'

    resultados = clean_light_curves(input_dir, output_dir, bad_hjds_list)
    

Processando arquivos: 100%|██████████| 8/8 [00:00<00:00, 23.67it/s]
